### ISSUE TITLE
Trouble getting Auth & World to authenticate

### ISSUE THREAD

**Issue by WaterlooJL** [StygianTheBest/StygianCore#55]
Help.  I'm a newb but not a dumb.  I've been trying to get your repack working on my machine for a week (about 30-60 minutes a day).

At a high level, what should I be doing to get the servers up and running?  I have the most recent builds of AzerothCore and StygianCore.

The symptom I get is the World and Auth servers can't connect:
![image](https://user-images.githubusercontent.com/50972750/58354322-157c0700-7e3f-11e9-98d6-fb50259838b1.png)

You can see in this case I followed the Install instructions from AC and copied files from the bin\debug folder.  I get the same thing if I try to run StygianCore out of the box (no recompile of AC), but the user in the error is Stygiancore.  So I have tried running StygianCore as a standalone download and also tried to compile the code locally via CMAKE.  When I run the Build in Visual Studio, I get no errors and two skipped files.

I suspect this is a really dumb question, which is why I have been trying to figure it out myself, but I'm out of things to retry.

Any ideas?  thanks for reading.

![image](https://user-images.githubusercontent.com/50972750/58354554-d8644480-7e3f-11e9-8058-f049e64066df.png)

**Comment by StygianTheBest** [comment]
The source code is available for advanced users, and I don't support compiling it, especially with later versions of AzerothCore I have not reviewed. I suggest getting a fresh copy of AzerothCore and learning how everything works first, the returning with that knowledge and working on implementing my modifications and additions in a staged process so you can identify and solve any issues that arise. 

I've tried to design my repack to be as easy as possible with clean code, comments, and documentation in and out of the code base. The source modifications are all noted in the docs, and all of the database work is separated and structured so that staging each addition should be easy. Good luck!

**Comment by WaterlooJL** [comment]
That's fair, thanks for the response.
